server:  servlet:    encoding:      charset: utf-8      enabeld: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "0000"
  
  jpa:
    hibernate:      ddl-auto: create
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    open-in-view: true    show-sql: true